microstrain_inertial_driver:
  ros__parameters:
    # Standalone example params file for GX3, GX4, GX/CX5, RQ1 and GQ7 series devices
    # Note: Feature support is device-dependent and some of the following settings may have no affect on your device.
    # Please consult your device's documentation for supported features

    # ******************************************************************
    # NOTE: This file is formatted to work with ROS and will not work if specified as the params_file argument in ROS2.
    #       If you want to override parameters for ROS2, start with https://github.com/LORD-MicroStrain/microstrain_inertial/blob/ros2/microstrain_inertial_driver/config/empty.yml
    # ******************************************************************

    # ******************************************************************
    # General Settings
    # ******************************************************************

    # port is the main port that the device will communicate over. For all devices except the GQ7, this is the only available port.
    # aux_port is only available for the GQ7 and is only needed when streaming RTCM corrections to the device from ROS, or if you want to publish NMEA sentences from this node
    port         : "/dev/whill"
    baudrate     : 115200
    debug        : False

    # If set to true, this will configure the requested baudrate on the device for the main port.
    # Note that this will be set on both USB and serial, but will only actually affect the baudrate of a serial connection.
    set_baud : False

    # Waits for a configurable amount of time until the device exists
    # If poll_max_tries is set to -1 we will poll forever until the device exists
    poll_port      : False
    poll_rate_hz   : 1.0
    poll_max_tries : 60

    # Number of times to attempt to reconnect to the device if it disconnects while running
    # If configure_after_reconnect is true, we will also reconfigure the device after we reconnect
    #
    # Note: It is strongly recommended to configure after reconnect unless device_setup is set to false
    #       as the device will likely initialize in a different state otherwise
    reconnect_attempts : 0
    configure_after_reconnect : True

    # Controls if the driver-defined setup is sent to the device
    #     false - The driver will ignore the settings below and use the device's current settings
    #     true  - Overwrite the current device settings with those listed below
    device_setup : True

    # Controls if the driver-defined settings are saved
    #     false - Do not save the settings
    #     true  - Save the settings in the device's non-volatile memory
    save_settings : False

    # Controls if the driver creates a raw binary file
    #     false - Do not create the file
    #     true  - Create the file
    #
    # Note: The filename will have the following format -
    #       model_number "_" serial_number "_" datetime (year_month_day_hour_minute_sec) ".bin"
    #           example: "3DM-GX5-45_6251.00001_20_12_01_01_01_01.bin"
    # Note: This file is useful for getting support from the manufacturer
    raw_file_enable : False

    # The directory to store the raw data file
    raw_file_directory : "/home/your_name"


    # ******************************************************************
    # Frame ID Settings
    # ******************************************************************

    # The mode in which we will publish transforms to the below frame IDs
    #     0 - No transforms will be published between any of the non static frame ids. (if publish_mount_to_frame_id_transform is true, it will still be published, and so will the antenna and odometer transforms)
    #     1 - Global mode:
    #             Transform will be published from earth_frame_id to target_frame_id containing global position
    #     2 - Relative mode:
    #             Note: In order to use relative mode, you must configure filter_relative_position
    #             Transform will be published from earth_frame_id to map_frame_id using relative position configuration
    #             Transform between map_frame_id and target_frame_id will be published using position information reported by the device
    # for more information, see: https://wiki.ros.org/microstrain_inertial_driver/transforms
    tf_mode : 0

    # Frame ID that most header.frame_id fields will be populated with.
    frame_id: "gx5"

    # Frame IDs determining the transforms published by this node to aid in navigation. See https://www.ros.org/reps/rep-0105.html
    # Note: If use_enu_frame is false, these frames (with the exception of earth_frame_id) will automatically have "_ned" appended to them.
    mount_frame_id     : "base_link"  # Frame ID that the device is mounted on.

    # Target frame ID to publish transform to. Note that there needs to be some path of transforms between this and frame_id
    #     If tf_mode is set to 1, a transform between earth_frame_id and target_frame_id will be published
    #     If tf_mode is set to 2, a transform between map_frame_id and target_frame_id will be published
    target_frame_id : "base_link"

    # Static transform between mount_frame_id and frame_id.
    # Note: It is recommended to define this in a urdf file if you are building a robot, or are able to modify the robot's description.
    publish_mount_to_frame_id_transform  : True
    mount_to_frame_id_transform          : [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0] # [ x, y, z, qi, qj, qk, qw ]

    # Controls if the driver outputs data with-respect-to ENU frame
    #     false - position, velocity, and orientation are WRT the NED frame (native device frame)
    #     true  - position, velocity, and orientation are WRT the ENU frame
    #
    # Note: It is strongly recommended to leave this as True if you plan to integrate with other ROS tools
    # Note: If this is set to false, all "*_frame_id" variables will have "_ned" appended to them by the driver.
    # For more information, see: https://wiki.ros.org/microstrain_inertial_driver/use_enu_frame
    use_enu_frame : True
    

    # Sensor2vehicle frame transformation selector
    #     0 = None
    #     1 = Euler Angles
    #     2 = matrix
    #     3 = quaternion
    # Note: These are different ways of setting the same parameter in the device.
    #       The different options are provided as a convenience.
    #       Support for matrix and quaternion options is firmware version dependent (GQ7 supports Quaternion as of firmware 1.0.07)
    #       Quaternion order is [i, j, k, w]
    # Note: This can cause strange behavior when also using the ROS transform tree.
    #       It is recommended to not use this if you want to use the ROS transform tree unless you really know what you are doing
    filter_sensor2vehicle_frame_selector : 1
    filter_sensor2vehicle_frame_transformation_euler      : [0.0, 0.0, 0.0]
    filter_sensor2vehicle_frame_transformation_matrix     : [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
    filter_sensor2vehicle_frame_transformation_quaternion : [0.0, 0.0, 0.0, 1.0]

    # Controls if the Kalman filter will auto-init or requires manual initialization
    filter_auto_init : True

    # Controls if the Kalman filter is reset after the settings are configured
    filter_reset_after_config : True

    # (All, except -10, and -15 products) Declination Source 1 = None, 2 = magnetic model, 3 = manual
    # Note: When using a CV7, this MUST be changed to either 1, or 3 or the node will not start
    filter_declination_source : 2
    filter_declination        : 0.23

    # Controls what kind of linear acceleration data is used in the Filter IMU message.
    #     If this is set to true, the acceleration will not factor out gravity, if set to false gravity will be filtered out of the linear acceleration.
    filter_use_compensated_accel : True

    # (GQ7/CV7 full support, GX5-45 limited support) Adaptive filter settings
    #     Adaptive level: 0 - off, 1 - Conservative, 2 = Moderate (default), 3 = agressive
    #     Time limit: Max duration of measurement rejection prior to recovery, in milliseconds - default = 15000
    filter_adaptive_level         : 2
    filter_adaptive_time_limit_ms : 15000

    # (All, except GQ7, CV7, -10, and -15 products) Heading Source 0 = None, 1 = magnetic, 2 = GNSS velocity (note: see manual for limitations)
    # Note: For the GQ7, this setting has no effect. See filter_auto_heading_alignment_selector
    # Note: When using a -10/-AR product. This MUST be set to 0 or the node will not start
    filter_heading_source : 1

    # (GX5 and previous,-45 models only) Dynamics Mode 1 = Portable (default), 2 = Automotive, 3 = Airborne (<2Gs), 4 = Airborne High G (<4Gs)
    filter_dynamics_mode : 1


    # ******************************************************************
    # IMU Settings
    # ******************************************************************

    # Static IMU message covariance values (the device does not generate these)
    imu_orientation_cov   : [0.01, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.01]
    imu_linear_cov        : [0.01, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.01]
    imu_angular_cov       : [0.01, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.01]
    imu_mag_cov           : [0.01, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.01]
    imu_pressure_variance : 0.01
    

    # ******************************************************************
    # Publisher Settings
    # ******************************************************************
    #
    #  Note: If set to 0, the data will not be stremaed from the device, and the publisher will not be created

    # The speed at which the individual IMU publishers will publish at.
    imu_data_rate             : 200  # Rate of imu/data topic
    imu_mag_data_rate         : 200    # Rate of imu/mag topic
    imu_pressure_data_rate    : 200  # Rate of imu/pressure topic
    imu_wheel_speed_data_rate : 200    # Rate of imu/wheel_Speed topic

    # The speed at which the individual Filter publishers will publish at.
    filter_human_readable_status_data_rate : 100  # Rate of ekf/status
    filter_imu_data_rate                   : 100  # Rate of ekf/imu/data topic
                                                # Note: Both filter_odometry_earth_data_rate and filter_odometry_map_data_rate depend on the contents of this message.
                                                #       If either are set to a higher value, this message will be published at that rate.
    filter_llh_position_data_rate          : 100  # Rate of ekf/llh_position topic
    filter_velocity_data_rate              : 100  # Rate of ekf/velocity topic
                                                # Note: filter_odometry_map_data_rate depends on the contents of this message.
                                                #       If either are set to a higher value, this message will be published at that rate.
    filter_velocity_ecef_data_rate         : 100  # Rate of ekf/velocity_ecef topic
                                                # Note: filter_odometry_earth_data_rate depends on the contents of this message.
                                                #       If either are set to a higher value, this message will be published at that rate.
    filter_odometry_earth_data_rate        : 25 # Rate of ekf/odometry_earth topic
    filter_odometry_map_data_rate          : 25 # Rate of ekf/odometry_map topic
