whill:
  ros__parameters:
    port_name: "/dev/whill"
    whill_publish_interval_ms: 10
    odom_publish_interval_ms: 50
    publish_odom_tf: true
    odom_frame_id: "odom"
    base_frame_id: "base_link"